In [4]:
# Why NumPy?

In [18]:
a = [1,2,3,4]
b = [2,3,4,5]


ab = []

for i in range(0,len(a)):
    ab.append(a[i]*b[i])
ab

In [19]:
import numpy as np

In [20]:
a = np.array([1,2,3,4])
b = np.array([2,3,4,5])

In [21]:
a*b

array([ 2,  6, 12, 20])

*Creating NumPy Array*

In [22]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [23]:
a = np.array([1,2,3,4,5])

In [24]:
type(a)

numpy.ndarray

In [30]:
np.array([3.14,4,2,13], dtype = int)

array([ 3,  4,  2, 13])

In [28]:
 # creating array from 0

In [29]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [31]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [32]:
np.full((3,5),2)

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [33]:
np.arange(0,31,3) # from zero to 31 increasing by 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30])

In [34]:
np.linspace(0,1,10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [35]:
np.random.normal(10,4,(3,4))

array([[ 8.72545549, 11.02766441, 13.95673016,  5.52129956],
       [15.13901893,  3.02613529, 14.20041563, 14.10766212],
       [ 2.02401427, 12.72908156,  6.00236026, 11.74547546]])

In [37]:
np.random.randint(0,10,(3,3))

array([[0, 5, 0],
       [5, 7, 6],
       [9, 1, 8]])

**Features of NumPy**

* **npdim:** number of dimensions
* shape: dimension information
* size: total number of elements
* dtype: array' data type

In [39]:
import numpy as np

In [41]:
a = np.random.randint(10,size=10)

In [42]:
a.ndim

1

In [43]:
a.shape

(10,)

In [44]:
a.size

10

In [45]:
a.dtype

dtype('int64')

In [46]:
b = np.random.randint(10,size=(3,5))

In [47]:
b

array([[3, 1, 6, 1, 7],
       [2, 4, 6, 0, 8],
       [2, 9, 7, 1, 5]])

In [48]:
b.ndim

2

In [49]:
b.shape

(3, 5)

In [50]:
b.size

15

In [51]:
b.dtype

dtype('int64')

# Array Reshaping

In [52]:
import numpy as np

In [53]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
np.arange(1,10).reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [60]:
a = np.arange(1,10)

In [61]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
a.ndim

1

In [66]:
b=a.reshape((1,9))

In [67]:
b.ndim

2

# Array Concatenation

In [68]:
import numpy as np

In [70]:
x = np.array([1,2,3])
y = np.array([4,5,6])

In [71]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [73]:
z = np.array([7,8,9])

In [74]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [75]:
# 2 Dimension

In [78]:
a = np.array([[1,2,3],[4,5,6]])

In [82]:
np.concatenate([a,a], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [81]:
np.concatenate([a,a], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

# Array Splitting

In [83]:
import numpy as np

In [85]:
x = np.array([1,2,3,99,99,3,2,1])

In [86]:
np.split(x,[3,5])

[array([1, 2, 3]), array([99, 99]), array([3, 2, 1])]

In [87]:
a,b,c = np.split(x,[3,5])

In [88]:
# 2 dimension splitting

In [89]:
m = np.arange(16).reshape(4,4)

In [90]:
m

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [92]:
upper,lower = np.vsplit(m,[2])

In [93]:
upper 

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [94]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [96]:
right,left = np.hsplit(m,[2])

In [97]:
right

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [98]:
left

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

# Sorting 

In [99]:
v = np.array([2,1,4,3,5])

In [100]:
v

array([2, 1, 4, 3, 5])

In [101]:
np.sort(v)

array([1, 2, 3, 4, 5])

In [104]:
v.sort()

In [105]:
v

array([1, 2, 3, 4, 5])

In [106]:
# 2 dimension array sorting

In [107]:
m = np.random.normal(20,5,(3,3))

In [108]:
m

array([[10.66388587,  7.42790666, 28.32023129],
       [15.74085596, 12.22826555, 16.80235177],
       [21.23373115, 25.93552653, 23.39068784]])

In [109]:
np.sort(m, axis = 1)

array([[ 7.42790666, 10.66388587, 28.32023129],
       [12.22826555, 15.74085596, 16.80235177],
       [21.23373115, 23.39068784, 25.93552653]])

In [110]:
np.sort(m,axis = 0)

array([[10.66388587,  7.42790666, 16.80235177],
       [15.74085596, 12.22826555, 23.39068784],
       [21.23373115, 25.93552653, 28.32023129]])

# Access to elements with index

In [111]:
import numpy as np
a = np.random.randint(10,size=10)
a

array([6, 5, 9, 0, 7, 1, 6, 4, 6, 1])

In [112]:
a[0]

6

In [113]:
a[-1]

1

In [114]:
a[0]=100

In [116]:
a

array([100,   5,   9,   0,   7,   1,   6,   4,   6,   1])

In [117]:
# two dimension

In [119]:
m = np.random.randint(10,size = (3,5))
m

array([[0, 5, 2, 3, 3],
       [6, 7, 8, 5, 6],
       [2, 2, 3, 7, 2]])

In [120]:
m[0,0]

0

In [121]:
m[1,1]

7

In [122]:
m[1,4]

6

In [123]:
m[1,4]=99
m

array([[ 0,  5,  2,  3,  3],
       [ 6,  7,  8,  5, 99],
       [ 2,  2,  3,  7,  2]])

In [124]:
m[1,4]=2.2

In [125]:
m

array([[0, 5, 2, 3, 3],
       [6, 7, 8, 5, 2],
       [2, 2, 3, 7, 2]])